spring:
  profiles:
    active: dev

info:
  application:
    name: springboot-api-rest-greisyGu-bussiness
    description: API REST from Maxikiosco GreisiGu
    author: Alex Lopez
    version: '@project.version@'

springdoc:
  swagger-ui:
    path: /

url:
  upload:
    windows: C://Windows//Temp//uploads//
    linux: /tmp/uploads/